enum GAME_STATES {
    WAITING_FOR_CONNECTION,
    PLACEMENT,
    WAITING_TO_PLAY,
    MY_TURN,
    OTHER_TURN,
    WIN,
    LOST
};

enum MIDI_MESSAGE_CODES {
    READY_FOR_CONNECTION,
    CONNECTION_RECEIVED
};